# Generated by Django 4.2.4 on 2023-08-31 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fiat', models.CharField(max_length=10)),
                ('crypto', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buyer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_id', models.CharField(blank=True, max_length=100, null=True)),
                ('usd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('Funds', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('btc_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_held', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_uid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='escrow_transaction_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.UUIDField(default=uuid.uuid4)),
                ('buyer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('btc_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_held', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_uid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('password', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('btc_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('wallet_address', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
